// Reprodução estrutural do arquivo C enviado: somente chamadas e métricas.
// Não executa C e não infere regiões pelos nomes.
export function criarCasoConvergente() {
  return [
    ["log_diagnostic", 1, []],
    ["arena_init", 0, []],
    ["arena_alloc", 3, []],
    ["arena_free", 1, []],
    ["hash_string", 3, []],
    ["avl_height", 0, []],
    ["avl_max", 0, []],
    ["avl_create_node", 4, ["arena_alloc"]],
    ["avl_right_rotate", 1, ["avl_max", "avl_height"]],
    ["avl_left_rotate", 1, ["avl_max", "avl_height"]],
    ["avl_get_balance", 0, ["avl_height"]],
    ["avl_insert", 20, ["avl_create_node", "avl_insert", "avl_max", "avl_height", "avl_get_balance", "avl_right_rotate", "avl_left_rotate"]],
    ["avl_find", 4, ["avl_find"]],
    ["chunk_init", 1, []],
    ["chunk_write", 3, []],
    ["chunk_add_constant", 3, []],
    ["chunk_free", 0, ["chunk_init"]],
    ["allocate_object", 2, []],
    ["create_string", 2, ["hash_string", "allocate_object"]],
    ["create_vector", 1, ["allocate_object"]],
    ["vector_push", 3, []],
    ["native_bitwise_transform_impl", 4, []],
    ["vm_reset_stack", 0, []],
    ["vm_init", 1, ["arena_init", "vm_reset_stack"]],
    ["vm_free_objects", 9, []],
    ["vm_free", 0, ["vm_free_objects", "arena_free"]],
    ["vm_push", 3, ["log_diagnostic"]],
    ["vm_pop", 3, ["log_diagnostic"]],
    ["vm_peek", 0, []],
    ["values_equal", 18, []],
    ["print_value", 24, []],
    ["vm_run", 102, ["vm_push", "vm_pop", "values_equal", "vm_peek"]],
    ["vm_interpret", 2, ["vm_reset_stack", "vm_push", "vm_run"]],
    ["serialize_chunk", 21, []],
    ["deserialize_chunk", 31, ["chunk_init"]],
    ["sample_kernel", 0, []],
    ["print_avl_node", 0, ["print_value"]],
    ["main", 40, ["vm_init", "create_string", "create_vector", "vector_push", "avl_insert", "avl_find", "print_value", "chunk_init", "chunk_add_constant", "chunk_write", "serialize_chunk", "chunk_free", "deserialize_chunk", "vm_interpret", "vm_pop", "vm_free"]],
  ].map(([nome, complexidade, chamadas]) => ({ nome, complexidade, chamadas }));
}
