name: Testes

on:
  push:
  pull_request:

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Executar testes
        run: npm test
